/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Model.Supplier;
import Model.SupplierDirectory;
import UI.Admin.AdminWorkAreaJPanel;
import UI.Supplier.SupplierWorkAreaJPanel;

/**
 *
 * @author Lufei
 */
public class LoginScreen extends javax.swing.JPanel {

    JPanel mainWorkArea;
    SupplierDirectory supplierDirectory;
    Supplier selectedSupplier = null;
    
    
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(JPanel mainWorkArea, SupplierDirectory supplierDirectory) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.supplierDirectory = supplierDirectory;
        
        populateRoleCombo();
        populateSupplierCombo();
        //updateSupplierVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        selectRoles = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        selectSuppliers = new javax.swing.JComboBox<>();
        lblSupplier = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Welcome to Lab 4");

        selectRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRolesActionPerformed(evt);
            }
        });

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Choose Your Role:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        selectSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSuppliersActionPerformed(evt);
            }
        });

        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplier.setText("Select Supplier:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRole, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectRoles, 0, 168, Short.MAX_VALUE)
                            .addComponent(selectSuppliers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblTitle)))
                .addContainerGap(425, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRole, lblSupplier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplier))
                .addGap(61, 61, 61)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSuppliersActionPerformed
        // TODO add your handling code here:
        if(selectSuppliers.getSelectedItem()==null)return;
        selectedSupplier=(Supplier)selectSuppliers.getSelectedItem();     
    }//GEN-LAST:event_selectSuppliersActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //JPanel selectedPanel=(JPanel)cmbRoles.getSelectedItem();
       /* if(selectedPanel.getClass()==SupplierWorkAreaJPanel.class)
            {   if(selectedSupplier==null){
                JOptionPane.showMessageDialog(this,"Please select a supplier to login under supplier role.");
                return;}
            else {
                selectedPanel=new SupplierWorkAreaJPanel(mainWorkArea, selectedSupplier);
                }
            }*/
       
       
       JPanel selectedPanel;
       int ss=selectRoles.getSelectedIndex();
       System.out.print(ss);
       if(ss==1){
           selectedPanel=new SupplierWorkAreaJPanel(mainWorkArea, selectedSupplier);
         if(selectedSupplier==null){
                JOptionPane.showMessageDialog(this,"Please select a supplier to login under supplier role.");
                return;}
        
            else {
                selectedPanel=new SupplierWorkAreaJPanel(mainWorkArea, selectedSupplier);
                }
       }
       else
           selectedPanel=new AdminWorkAreaJPanel(mainWorkArea, supplierDirectory);
        
        
        mainWorkArea.add("WorkAreaJPanel",selectedPanel);
        CardLayout layout =(CardLayout)mainWorkArea.getLayout();
        layout.next(mainWorkArea);
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void selectRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRolesActionPerformed
        // TODO add your handling code here:
        updateSupplierVisibility();
    }//GEN-LAST:event_selectRolesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JComboBox<Object> selectRoles;
    private javax.swing.JComboBox<Supplier> selectSuppliers;
    // End of variables declaration//GEN-END:variables

    private void populateRoleCombo() {
        selectRoles.removeAllItems();
        AdminWorkAreaJPanel ap = new AdminWorkAreaJPanel(mainWorkArea, supplierDirectory);
        SupplierWorkAreaJPanel sp=new SupplierWorkAreaJPanel(mainWorkArea,selectedSupplier);
        selectRoles.addItem(ap.toString());
        selectRoles.addItem(sp.toString());
      

    }

    public void populateSupplierCombo() {
        selectSuppliers.removeAllItems();
        for(Supplier supplier : supplierDirectory.getSupplierList()){
            selectSuppliers.addItem(supplier);
        }
     
       
    }

    private void updateSupplierVisibility() {
        if(selectRoles.getSelectedIndex()==0)
        {
            selectedSupplier=null;
            lblSupplier.setVisible(false);
            selectSuppliers.setVisible(false);
        }
        else
        {
            lblSupplier.setVisible(true);
            selectSuppliers.setVisible(true);
        }
        
        
         //To change body of generated methods, choose Tools | Templates.
    }
}
