/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.common;
import ui.admin.AdminWorkArea;
import ui.customer.CustomerWorkArea;
import ui.manager.ManagerWorkArea;
import java.awt.CardLayout;
import model.LibrarySystem;
import model.ConfigureTheBusiness;
import model.UserAccount;


/**
 *
 * @author l
 */
public class AppFrame extends javax.swing.JFrame {


    private CardLayout card;
    private LibrarySystem system;
    private java.util.List<model.Book> sharedBooks = new java.util.ArrayList<>();
    private java.util.List<model.RentalRecord> sharedRecords = new java.util.ArrayList<>();
    private model.Library sharedLibrary;

    public AppFrame() {
        initComponents();
        setLocationRelativeTo(null);

        system = model.ConfigureTheBusiness.init(); 

        sharedBooks.addAll(system.getBooks());            
        sharedRecords.addAll(system.getRentalRecords());   
        sharedLibrary = system.getLibraries().get(0);     

        card = (java.awt.CardLayout) rootPanel.getLayout();
        rootPanel.add("Login", new ui.common.LoginPanel(rootPanel, card, system));
        card.show(rootPanel, "Login");
    }

    public void showAdmin(UserAccount me) {
        if (rootPanel.getClientProperty("has_Admin") == null) {
            rootPanel.add("Admin", new AdminWorkArea(system, me));
            rootPanel.putClientProperty("has_Admin", true);
        }
        card.show(rootPanel, "Admin");
    }

    public void showManager(model.UserAccount me) {
        if (rootPanel.getClientProperty("has_Manager") == null) {
            ui.manager.ManagerWorkArea mwa = new ui.manager.ManagerWorkArea(me);
            mwa.bindData(sharedBooks, sharedRecords, sharedLibrary);
            rootPanel.add("Manager", mwa);
            rootPanel.putClientProperty("has_Manager", true);
        }
        card.show(rootPanel, "Manager");
    }


    public void showCustomer(model.UserAccount me) {
        if (rootPanel.getClientProperty("has_Customer") == null) {
            ui.customer.CustomerWorkArea cwa = new ui.customer.CustomerWorkArea(system, me);
            cwa.bindData(sharedBooks, sharedRecords, sharedLibrary); // 共享
            rootPanel.add("Customer", cwa);
            rootPanel.putClientProperty("has_Customer", true);
        }
        card.show(rootPanel, "Customer");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(rootPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables
}
