/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Product;
import model.ProductCatalog;

/**
 *
 * @author l
 */
public class ManageProductsPanel extends javax.swing.JPanel {


    private final JPanel workArea;       
    private final ProductCatalog catalog;   
    /**
     * Creates new form ManageProductsPanel
     */
    public ManageProductsPanel
        
        (JPanel workArea, ProductCatalog catalog) {
        initComponents();
        this.workArea = workArea;
        this.catalog = catalog;

        try {
            JComboBox<Category> catEditor = new JComboBox<>(Category.values());
            tblProducts.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(catEditor));
        } catch (Exception ignore) {}

        refreshTable();

    }
    
    private void refreshTable() {
        DefaultTableModel m = (DefaultTableModel) tblProducts.getModel();
        m.setRowCount(0);
        for (Product p : catalog.getAll()) {
            m.addRow(new Object[]{
                p.getProductId(),
                p.getName(),
                p.getCategory(),
                p.getPrice(),
                p.getQuantity(),
                p.getPreparationMinutes()
            });
        }
    }

    private void onAddRow() {
        ((DefaultTableModel) tblProducts.getModel())
                .addRow(new Object[]{null, "", Category.COFFEE, null, null, null});
    }

    private void onDelete() {
        int[] rows = tblProducts.getSelectedRows();
        if (rows.length == 0) {
            JOptionPane.showMessageDialog(this, "Select at least one row.");
            return;
        }
        DefaultTableModel m = (DefaultTableModel) tblProducts.getModel();
        for (int i = rows.length - 1; i >= 0; i--) m.removeRow(rows[i]);
    }

    private void onSave() {
        DefaultTableModel m = (DefaultTableModel) tblProducts.getModel();
        List<Product> list = new ArrayList<>();

        for (int r = 0; r < m.getRowCount(); r++) {
            Object idObj = m.getValueAt(r,0);
            Object nameObj = m.getValueAt(r,1);
            if (idObj==null || nameObj==null || nameObj.toString().trim().isEmpty()) continue;

            Product p = new Product();
            try { p.setProductId(Integer.parseInt(idObj.toString())); }
            catch(Exception e){ JOptionPane.showMessageDialog(this,"Row "+(r+1)+" ID invalid"); return; }

            p.setName(nameObj.toString());
            p.setCategory((Category) m.getValueAt(r,2));
            try { p.setPrice(Double.parseDouble(m.getValueAt(r,3).toString())); } catch(Exception ignore){}
            try { p.setQuantity(Integer.parseInt(m.getValueAt(r,4).toString())); } catch(Exception ignore){}
            try { p.setPreparationMinutes(Integer.parseInt(m.getValueAt(r,5).toString())); } catch(Exception ignore){}

            list.add(p);
        }

        catalog.getAll().clear();
        for (Product p : list) catalog.add(p);
        JOptionPane.showMessageDialog(this, "Saved " + list.size() + " product(s).");
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnAddRow = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Number", "Prep Time"
            }
        ));
        tblProducts.setRowHeight(24);
        jScrollPane1.setViewportView(tblProducts);

        btnAddRow.setText("Add Row");
        btnAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRowActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Selected");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnAddRow)
                        .addGap(31, 31, 31)
                        .addComponent(btnDelete)
                        .addGap(30, 30, 30)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRow)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRowActionPerformed
        // TODO add your handling code here:
        onAddRow();
    }//GEN-LAST:event_btnAddRowActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        onDelete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        onSave();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
