/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.*;
import javax.swing.JPanel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;


/**
 *
 * @author l
 */
public class SearchCustomersPanel extends JPanel {

    private JPanel workArea;
    private CustomerDirectory customerDirectory;
    private OrderDirectory orderDirectory;

    public SearchCustomersPanel() { initComponents(); }


    public SearchCustomersPanel(JPanel workArea,
                                CustomerDirectory cdir,
                                OrderDirectory odir) {
        this(); 
        this.workArea = workArea;
        this.customerDirectory = cdir;
        this.orderDirectory = odir;
    }
    
    private void fillTable(java.util.List<model.Customer> list){
        DefaultTableModel m = (DefaultTableModel) tblCustomers.getModel();
        m.setRowCount(0);
        if (list == null) return;
        for (model.Customer c : list) {
            String full = (c.getFirstName()==null?"":c.getFirstName()) + " " + (c.getLastName()==null?"":c.getLastName());
            int orders = (c.getOrders()==null) ? 0 : c.getOrders().size();
            m.addRow(new Object[]{ c.getCustomerId(), full.trim(), c.getContact(), orders });
        }
    }

    private void msg(String s){ JOptionPane.showMessageDialog(this, s); }
    private Integer parseInt(String s, String label){
        try { return Integer.parseInt(s.trim()); }
        catch(Exception e){ msg(label+" must be an integer."); return null; }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchId = new javax.swing.JTextField();
        btnSearchById = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        btnSearchByName = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtFirst = new javax.swing.JTextField();
        txtLast = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();

        jLabel1.setText("Customer ID:");

        txtSearchId.setPreferredSize(new java.awt.Dimension(120, 23));

        btnSearchById.setText("Search by ID");
        btnSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        txtSearchName.setPreferredSize(new java.awt.Dimension(120, 23));

        btnSearchByName.setText("Search by Name");
        btnSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByNameActionPerformed(evt);
            }
        });

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Full Name", "Phone", "Orders#"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Contact:");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtFirst.setPreferredSize(new java.awt.Dimension(120, 23));

        txtLast.setPreferredSize(new java.awt.Dimension(120, 23));

        txtContact.setPreferredSize(new java.awt.Dimension(120, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchByName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearchById, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnUpdate)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(btnSearchById))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSearchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchByName))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByIdActionPerformed
        Integer id = parseInt(txtSearchId.getText(), "Customer ID"); if (id==null) return;
        model.Customer c = customerDirectory.findById(id);
        if (c == null) { msg("Not found."); fillTable(java.util.Collections.emptyList()); return; }
        fillTable(java.util.Arrays.asList(c));

        txtFirst.setText(c.getFirstName()==null?"":c.getFirstName());
        txtLast.setText(c.getLastName()==null?"":c.getLastName());
        txtContact.setText(c.getContact()==0 ? "" : String.valueOf(c.getContact()));        
    }//GEN-LAST:event_btnSearchByIdActionPerformed

    private void btnSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByNameActionPerformed
        String q = txtSearchName.getText()==null ? "" : txtSearchName.getText().trim().toLowerCase();
        java.util.List<model.Customer> res = new java.util.ArrayList<>();
        for (model.Customer c : customerDirectory.getAll()) {
            String full = ((c.getFirstName()==null?"":c.getFirstName()) + " " + (c.getLastName()==null?"":c.getLastName())).toLowerCase();
            if (full.contains(q)) res.add(c);
        }
        if (res.isEmpty()) msg("No matches.");
        fillTable(res);     
    }//GEN-LAST:event_btnSearchByNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblCustomers.getSelectedRow();
        if (row < 0) { msg("Select a row first."); return; }
        int id = Integer.parseInt(tblCustomers.getValueAt(row,0).toString());
        model.Customer c = customerDirectory.findById(id);
        if (c == null) { msg("Customer not found."); return; }

        c.setFirstName(txtFirst.getText()==null?"":txtFirst.getText().trim());
        c.setLastName(txtLast.getText()==null?"":txtLast.getText().trim());
        try { c.setContact(Long.parseLong(txtContact.getText().trim())); } catch(Exception ignore){}

        msg("Updated.");

        java.util.List<model.Customer> cur = new java.util.ArrayList<>();
        for (int r=0; r<tblCustomers.getRowCount(); r++){
            int cid = Integer.parseInt(tblCustomers.getValueAt(r,0).toString());
            model.Customer cc = customerDirectory.findById(cid);
            if (cc!=null) cur.add(cc);
        }
        fillTable(cur);     
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblCustomers.getSelectedRow();
        if (row < 0) return;
        Object idObj = tblCustomers.getValueAt(row, 0);
        if (idObj == null) return;
        int id = Integer.parseInt(idObj.toString());
        model.Customer c = customerDirectory.findById(id);
        if (c == null) return;
        txtFirst.setText(c.getFirstName()==null?"":c.getFirstName());
        txtLast.setText(c.getLastName()==null?"":c.getLastName());
        txtContact.setText(c.getContact()==0 ? "" : String.valueOf(c.getContact()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchById;
    private javax.swing.JButton btnSearchByName;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtSearchId;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables
}
