/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.customer;

import model.Author;
import model.Book;
import model.Library;
import model.RentalRecord;
import model.UserAccount;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author l
 */
public class CustomerWorkArea extends javax.swing.JPanel {
    private final UserAccount currentUser;
    private List<Book> books = new ArrayList<>();
    private List<RentalRecord> records = new ArrayList<>();
    private Library library;

    private final List<Book> filteredBooks = new ArrayList<>();
    private BookTableModel bookTableModel;
    private MyRentalTableModel rentalTableModel;

    public CustomerWorkArea(model.LibrarySystem unused, UserAccount currentUser) {
        this.currentUser = currentUser;
        initComponents();
        initAfterDesigner();
    }

    public void bindData(List<Book> books, List<RentalRecord> records, Library library) {
        this.books = books != null ? books : new ArrayList<>();
        this.records = records != null ? records : new ArrayList<>();
        this.library = library;
        reloadBooks();
        refreshBookTable();
        refreshMyRentals();
    }

    private void initAfterDesigner() {
        bookTableModel = new BookTableModel();
        tblBooks.setModel(bookTableModel);
        rentalTableModel = new MyRentalTableModel();
        tblMyRentals.setModel(rentalTableModel);
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        btnReset.addActionListener(this::btnResetActionPerformed);
        btnBorrowSelected.addActionListener(this::btnBorrowSelectedActionPerformed);
        btnReturnSelected.addActionListener(this::btnReturnSelectedActionPerformed);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfKeyword = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        btnBorrowSelected = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMyRentals = new javax.swing.JTable();
        btnReturnSelected = new javax.swing.JButton();

        jLabel1.setText("key word");

        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setText("reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Branch", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBooks);

        btnBorrowSelected.setText("Borrow Selected");
        btnBorrowSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBorrowSelected)
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBorrowSelected)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Browse", jPanel1);

        tblMyRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "RecordID", "Book", "Branch", "BorrowedOn", "ReturnedOn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMyRentals);

        btnReturnSelected.setText("Return Selected");
        btnReturnSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturnSelected)
                .addGap(249, 249, 249))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnReturnSelected)
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("My Rentals", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String kw = tfKeyword.getText().trim().toLowerCase();
        filteredBooks.clear();
        if (kw.isEmpty()) {
            filteredBooks.addAll(books);
        } else {
            for (Book b : books) {
                String title = b.getName() == null ? "" : b.getName().toLowerCase();
                String author = (b.getAuthor() != null && b.getAuthor().getName() != null)
                        ? b.getAuthor().getName().toLowerCase() : "";
                if (title.contains(kw) || author.contains(kw)) filteredBooks.add(b);
            }
        }
        refreshBookTable();   
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfKeyword.setText("");
        reloadBooks();
        refreshBookTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBorrowSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowSelectedActionPerformed
        int row = tblBooks.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a book to borrow.");
            return;
        }
        Book b = filteredBooks.get(row);
        if (b.isRented()) {
            JOptionPane.showMessageDialog(this, "This book is already rented.");
            return;
        }
        RentalRecord rr = new RentalRecord(b, currentUser, library);
        records.add(rr);
        b.setRented(true);
        refreshMyRentals();
        refreshBookTable();
        JOptionPane.showMessageDialog(this, "Borrowed: " + b.getName());
    }//GEN-LAST:event_btnBorrowSelectedActionPerformed

    private void btnReturnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSelectedActionPerformed
        int row = tblMyRentals.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select a record to return.");
            return;
        }
        RentalRecord rr = rentalTableModel.getAt(row);
        if (rr.getStatus() == RentalRecord.Status.RETURNED) {
            JOptionPane.showMessageDialog(this, "Already returned.");
            return;
        }
        rr.markReturned();
        if (rr.getBook() != null) rr.getBook().setRented(false);
        refreshMyRentals();
        refreshBookTable();
        JOptionPane.showMessageDialog(this, "Returned: " + rr.getBook().getName());
    }//GEN-LAST:event_btnReturnSelectedActionPerformed
    
    private void reloadBooks() {
        filteredBooks.clear();
        filteredBooks.addAll(books);
    }

    private void refreshBookTable() {
        bookTableModel.setData(filteredBooks);
    }

    private void refreshMyRentals() {
        List<RentalRecord> mine = new ArrayList<>();
        for (RentalRecord r : records) {
            if (r.getCustomer() != null && r.getCustomer().equals(currentUser)) mine.add(r);
        }
        rentalTableModel.setData(mine);
    }

    private static class BookTableModel extends AbstractTableModel {
        private final String[] cols = {"SN", "Title", "Author", "Language", "Rented?"};
        private List<Book> data = new ArrayList<>();
        void setData(List<Book> d) { this.data = d; fireTableDataChanged(); }
        @Override public int getRowCount() { return data == null ? 0 : data.size(); }
        @Override public int getColumnCount() { return cols.length; }
        @Override public String getColumnName(int c) { return cols[c]; }
        @Override public Object getValueAt(int r, int c) {
            Book b = data.get(r);
            return switch (c) {
                case 0 -> b.getSerialNumber();
                case 1 -> b.getName();
                case 2 -> b.getAuthor() == null ? "-" : b.getAuthor().getName();
                case 3 -> b.getLanguage();
                case 4 -> b.isRented() ? "Yes" : "No";
                default -> "";
            };
        }
    }

    private static class MyRentalTableModel extends AbstractTableModel {
        private final String[] cols = {"RecordID", "Book", "RentedAt", "ReturnedAt", "Status"};
        private final SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        private List<RentalRecord> data = new ArrayList<>();
        void setData(List<RentalRecord> d) { this.data = d; fireTableDataChanged(); }
        RentalRecord getAt(int r) { return data.get(r); }
        @Override public int getRowCount() { return data == null ? 0 : data.size(); }
        @Override public int getColumnCount() { return cols.length; }
        @Override public String getColumnName(int c) { return cols[c]; }
        @Override public Object getValueAt(int r, int c) {
            RentalRecord rr = data.get(r);
            return switch (c) {
                case 0 -> rr.getId();
                case 1 -> rr.getBook() == null ? "-" : rr.getBook().getName();
                case 2 -> rr.getRentedAt() == null ? "-" : df.format(java.sql.Timestamp.valueOf(rr.getRentedAt()));
                case 3 -> rr.getReturnedAt() == null ? "-" : df.format(java.sql.Timestamp.valueOf(rr.getReturnedAt()));
                case 4 -> rr.getStatus();
                default -> "";
            };
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrowSelected;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReturnSelected;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTable tblMyRentals;
    private javax.swing.JTextField tfKeyword;
    // End of variables declaration//GEN-END:variables
}
