/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.manager;
import model.Author;
import model.Book;
import model.Library;
import model.RentalRecord;
import model.UserAccount;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author l
 */
public class ManagerWorkArea extends javax.swing.JPanel {

    private final UserAccount currentUser;
    private Library library;
    private List<Book> books = new ArrayList<>();
    private List<RentalRecord> records = new ArrayList<>();

    private BookTableModel bookModel;
    private RentalTableModel rentalModel;

    public ManagerWorkArea(UserAccount currentUser) {
        this.currentUser = currentUser;
        initComponents();
        initAfterDesigner();
    }

    public void bindData(List<Book> books, List<RentalRecord> records, Library library) {
        this.books = books != null ? books : new ArrayList<>();
        this.records = records != null ? records : new ArrayList<>();
        this.library = library;
        refreshBooks();
        refreshRentals();
    }

    private void initAfterDesigner() {
        bookModel = new BookTableModel();
        tblBooks.setModel(bookModel);
        rentalModel = new RentalTableModel();
        tblRentals.setModel(rentalModel);

        if (!(spPages.getModel() instanceof SpinnerNumberModel)) {
            spPages.setModel(new SpinnerNumberModel(200, 1, 10000, 1));
        }

        btnAddBook.addActionListener(this::btnAddBookActionPerformed);
        btnDeleteBook.addActionListener(this::btnDeleteBookActionPerformed);
        btnMarkReturned.addActionListener(this::btnMarkReturnedActionPerformed);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        lblPages = new javax.swing.JLabel();
        spPages = new javax.swing.JSpinner();
        lblLang = new javax.swing.JLabel();
        tfLanguage = new javax.swing.JTextField();
        lblAuthor = new javax.swing.JLabel();
        tfAuthor = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        btnDeleteBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRentals = new javax.swing.JTable();
        btnMarkReturned = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblTitle.setText("Title");

        lblPages.setText("Pages");

        lblLang.setText("Language");

        lblAuthor.setText("Author");

        btnAddBook.setText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDeleteBook.setText("Delete Selected");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SN", "Title", "Author", "Language", "Rented"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBooks);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblAuthor)
                                .addGap(18, 18, 18)
                                .addComponent(tfAuthor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLang)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitle)
                                        .addComponent(lblPages)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(spPages)
                                    .addComponent(tfLanguage))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnAddBook)
                        .addGap(54, 54, 54)
                        .addComponent(btnDeleteBook)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPages)
                            .addComponent(spPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLang)
                            .addComponent(tfLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAuthor)
                            .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnDeleteBook))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Books", jPanel1);

        tblRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RecordID", "Book", "Customer", "RentedAt", "ReturnedAt", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblRentals);

        btnMarkReturned.setText("Mark Returned");
        btnMarkReturned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkReturnedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnMarkReturned)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnMarkReturned)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rentals", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        String title = tfTitle.getText().trim();
        String lang  = tfLanguage.getText().trim();
        String authorName = tfAuthor.getText().trim();
        int pages = ((Number) spPages.getValue()).intValue();

        if (title.isEmpty() || authorName.isEmpty() || lang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title/Author/Language are required.");
            return;
        }

        Author author = new Author(authorName);
        Book b = new Book(title, pages, lang, author);
        books.add(b);

        tfTitle.setText("");
        tfLanguage.setText("");
        tfAuthor.setText("");
        spPages.setValue(200);

        refreshBooks();
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        int row = tblBooks.getSelectedRow();
        if (row < 0) return;
        Book b = bookModel.getAt(row);
        if (b.isRented()) {
            JOptionPane.showMessageDialog(this, "Cannot delete a rented book.");
            return;
        }
        books.remove(b);
        refreshBooks();
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void btnMarkReturnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkReturnedActionPerformed
        int row = tblRentals.getSelectedRow();
        if (row < 0) return;
        RentalRecord rr = rentalModel.getAt(row);

        if (rr.getStatus() == RentalRecord.Status.RETURNED) {
            JOptionPane.showMessageDialog(this, "Already returned.");
            return;
        }
        rr.markReturned();
        if (rr.getBook() != null) rr.getBook().setRented(false);
        refreshBooks();
        refreshRentals();
    }//GEN-LAST:event_btnMarkReturnedActionPerformed

    private void refreshBooks() {
        bookModel.setData(new ArrayList<>(books));
    }

    private void refreshRentals() {
        List<RentalRecord> list = new ArrayList<>();
        for (RentalRecord r : records) {
            if (library == null || r.getLibrary() == null) {
                list.add(r);
            } else if (r.getLibrary().equals(library)) {
                list.add(r);
            }
        }
        rentalModel.setData(list);
    }

    private static class BookTableModel extends AbstractTableModel {
        private final String[] cols = {"SN", "Title", "Author", "Language", "Rented?"};
        private List<Book> data = new ArrayList<>();
        void setData(List<Book> d) { this.data = d; fireTableDataChanged(); }
        Book getAt(int r) { return data.get(r); }
        @Override public int getRowCount() { return data == null ? 0 : data.size(); }
        @Override public int getColumnCount() { return cols.length; }
        @Override public String getColumnName(int c) { return cols[c]; }
        @Override public Object getValueAt(int r, int c) {
            Book b = data.get(r);
            return switch (c) {
                case 0 -> b.getSerialNumber();
                case 1 -> b.getName();
                case 2 -> b.getAuthor() == null ? "-" : b.getAuthor().getName();
                case 3 -> b.getLanguage();
                case 4 -> b.isRented() ? "Yes" : "No";
                default -> "";
            };
        }
    }

    private static class RentalTableModel extends AbstractTableModel {
        private final String[] cols = {"RecordID","Book","Customer","RentedAt","ReturnedAt","Status"};
        private final SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        private List<RentalRecord> data = new ArrayList<>();
        void setData(List<RentalRecord> d) { this.data = d; fireTableDataChanged(); }
        RentalRecord getAt(int r) { return data.get(r); }
        @Override public int getRowCount() { return data == null ? 0 : data.size(); }
        @Override public int getColumnCount() { return cols.length; }
        @Override public String getColumnName(int c) { return cols[c]; }
        @Override public Object getValueAt(int r, int c) {
            RentalRecord rr = data.get(r);
            return switch (c) {
                case 0 -> rr.getId();
                case 1 -> rr.getBook() == null ? "-" : rr.getBook().getName();
                case 2 -> rr.getCustomer() == null ? "-" : rr.getCustomer().getDisplayName();
                case 3 -> rr.getRentedAt() == null ? "-" : df.format(java.sql.Timestamp.valueOf(rr.getRentedAt()));
                case 4 -> rr.getReturnedAt() == null ? "-" : df.format(java.sql.Timestamp.valueOf(rr.getReturnedAt()));
                case 5 -> rr.getStatus();
                default -> "";
            };
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnMarkReturned;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lblPages;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner spPages;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTable tblRentals;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfLanguage;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
}
